### ISSUE TITLE
bug: new projects template should use latest process_lib release tag

### ISSUE THREAD

**Issue by dr-frmr** [kinode-dao/kit#144]
**Describe the bug**
Currently process templates use a random outdated process_lib library revision.

**To Reproduce**
1. Create a new app with `kit new`
2. Go to Cargo.toml for a process

**Expected behavior**
Process library version should be pulled from here: https://github.com/kinode-dao/process_lib/releases

**Comment by nick1udwig** [comment]
This is an ongoing one, but updated to 0.8.3 here: https://github.com/kinode-dao/kit/pull/191/commits/a8457d7179f389195218b67519e70611413b227e
