### ISSUE TITLE
feature: `kit update` log while running

### ISSUE THREAD

**Issue by jurij-jukic** [kinode-dao/kit#150]
**Is your feature request related to a problem? Please describe.**
I run `kit update` and there is no output. It takes like 1min to run on my mac, so I'm not sure if it's working or not.

**Describe the solution you'd like**
A simple output saying sth like "kit update in progress..."

**Additional context**
MacOS Intel,
Kit 0.4.0

**Comment by nick1udwig** [comment]
b9f13a5
