### ISSUE TITLE
feature: kit publish

### ISSUE THREAD

**Issue by bitful-pannul** [kinode-dao/kit#176]
**Is your feature request related to a problem? Please describe.**
When deploying apps to the app_store, there are a couple pitfalls that a developer can fall in: hash mismatch, mirrors, publisher not being the nodes address.

**Describe the solution you'd like**
`kit publish`

**Notes**
Private key can live in .env or be passed in. Can autofill hashes by doing a `kit s´ if no latest metadata hash is filled in.

**Comment by nick1udwig** [comment]
As discussed in the chat -- I'm pretty wary of putting private keys in `.env`. I think its acceptable short-term if we have a plan to:
1. Delegate, as, I believe dolled-possum suggested, so users don't have to put keys holding $ in `.env`,
2. Some other more secure method that doesn't involve writing private keys in plaintext.
