### ISSUE TITLE
bug: build should swap `-` to `_` for grabbing .wasm files

### ISSUE THREAD

**Issue by dr-frmr** [kinode-dao/kit#216]
**Describe the bug**

```
ERROR src/main.rs:1195:
   0: Command `wasm-tools ["component", "new", "target/wasm32-wasi/release/kimap-explorer.wasm", "-o", "../pkg/kimap-explorer.wasm", "--adapt", "target/wasi_snapshot_preview1.wasm"]` failed with exit code Some(1)
      stdout:
      stderr: error: failed to read from `target/wasm32-wasi/release/kimap-explorer.wasm`

      Caused by:
          0: No such file or directory (os error 2)
   0:

Location:
   src/build/mod.rs:190

  ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ SPANTRACE ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

   0: kit::build::run_command
      at src/build/mod.rs:165
   1: kit::build::compile_rust_wasm_process
      at src/build/mod.rs:487
   2: kit::build::compile_package_item
      at src/build/mod.rs:721
```

**To Reproduce**
1. create app with `-` in name
2. try to build

**Expected behavior**
build should expect that cargo/wasm will swap hyphens to underscores and try to match that (annoying) behavior

**Comment by nick1udwig** [comment]
This is a p annoying thing that results from:
1. cargo doesn't like `-`s and wants `_`s
2. App Store doesn't like `_`s and wants `-`s

**Comment by nick1udwig** [comment]
Note this is already an outstanding issue with cargo: lots of crates are imported with `-`s but have package names with `_`s

P bad

To get it to work currently w our system you can have all cargo stuff with `_`s and `metadata.json` with `-`s, but I agree it is quite brittle

**Comment by nick1udwig** [comment]
#222

**Comment by nick1udwig** [comment]
#222

**Comment by nick1udwig** [comment]
Ah; not quite right. `kit s` needs a little more work

**Comment by nick1udwig** [comment]
#226

**Comment by nick1udwig** [comment]
#257
