### ISSUE TITLE
kit: should display appropriate message when not finding on chain metadata.json in app directory

### ISSUE THREAD

**Issue by bitful-pannul** [kinode-dao/kit#99]
tbd

**Comment by nick1udwig** [comment]
In general we need better error messaging. I did some work to at least get rough line numbers -- which helps for reporting, but not the "non-nerdview errors" problem.

**Comment by nick1udwig** [comment]
Rolling this into #104

**Comment by nick1udwig** [comment]
It has begun https://github.com/kinode-dao/kit/commit/9dea825fc4142c7c8c7c603afa4bf2e6e1e5f354
